---
abstract: 'mark strings as HTML to get auto-escaping'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-String
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::EndOfScope: 0.11
  Data::Munge: 0.04
  Safe::Isa: 1
  UNIVERSAL::ref: 0.14
  strictures: 1
version: 1.000001
